"""Domain contracts for the browser testing agent."""

from browser_agent.domain.models import (
    ActionApproval,
    ActionResult,
    ApprovalPolicyDecision,
    BrowserAction,
    BrowserActionType,
    BrowserTarget,
    BrowserTargetStrategy,
    BugReport,
    BugSeverity,
    ExecutionStep,
    ExpectedResultCheck,
    FailureCategory,
    FailureClassification,
    JudgeVerdict,
    RunReport,
    RunTermination,
    TerminationKind,
    TestCase,
)

__all__ = [
    "ActionApproval",
    "ActionResult",
    "ApprovalPolicyDecision",
    "BrowserAction",
    "BrowserActionType",
    "BrowserTarget",
    "BrowserTargetStrategy",
    "BugReport",
    "BugSeverity",
    "ExecutionStep",
    "ExpectedResultCheck",
    "FailureCategory",
    "FailureClassification",
    "JudgeVerdict",
    "RunReport",
    "RunTermination",
    "TerminationKind",
    "TestCase",
]
